branches:
   only: gh-pages
language: erlang
otp_release: 17.4
script:
  - ./maybe_handle_PR.sh $TRAVIS_PULL_REQUEST $TRAVIS_BUILD_DIR
  - find . -name meta.txt | cut -c3- | sed 's/.........$//' >_
  - wc -l _
